import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import productsRouter from "./products";
import categoriesRouter from "./categories";
import bannersRouter from "./banners";
import ordersRouter from "./orders";
import usersRouter from "./users";
import couponsRouter from "./coupons";
import walletRouter from "./wallet";
import dashboardRouter from "./dashboard";
import storageRouter from "./storage";
import notificationsRouter from "./notifications";
import importExportRouter from "./import-export";
import integrationsRouter from "./integrations";
import syncJobsRouter from "./sync-jobs";
import couriersRouter from "./couriers";
import paymentsRouter from "./payments";
import locationsRouter from "./locations";
import whatsappRouter from "./whatsapp";
import siteSettingsRouter from "./siteSettings";
import seoRouter from "./seo";
import blogPostsRouter from "./blogPosts";
import abandonedCheckoutsRouter from "./abandonedCheckouts";
import addressesRouter from "./addresses";
import adminProfileRouter from "./adminProfile";
import announcementsRouter from "./announcements";
import footerRouter from "./footer";
import aiRouter from "./ai";
import failedOrdersRouter from "./failedOrders";
import adminNotificationsRouter from "./adminNotifications";
import chatRouter from "./chat";
import reviewsRouter from "./reviews";
import searchRouter from "./search";
import imageUploadRouter from "./imageUpload";
import emailSettingsRouter from "./emailSettings";
import shippingRouter from "./shipping";
import headerSettingsRouter from "./headerSettings";
import bidsRouter from "./bids";
import restockRouter from "./restock";
import shopifyRouter from "./shopify";
import waInboxRouter from "./waInbox";
import socialRouter from "./social";
import intelligenceRouter from "./intelligence";
import meezanRouter from "./meezan";
import ridersRouter from "./riders";
import ridersPortalRouter from "./riders-portal";
import branchesRouter from "./branches";
import branchInvoiceRouter from "./branch-invoice";
import erpSettingsRouter from "./erp-settings";
import branchStockRouter from "./branch-stock";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(productsRouter);
router.use(categoriesRouter);
router.use(bannersRouter);
router.use(ordersRouter);
router.use(usersRouter);
router.use(couponsRouter);
router.use(walletRouter);
router.use(dashboardRouter);
router.use(storageRouter);
router.use(notificationsRouter);
router.use(importExportRouter);
router.use(integrationsRouter);
router.use(syncJobsRouter);
router.use(couriersRouter);
router.use(paymentsRouter);
router.use(locationsRouter);
router.use(whatsappRouter);
router.use(siteSettingsRouter);
router.use(seoRouter);
router.use(blogPostsRouter);
router.use(abandonedCheckoutsRouter);
router.use(addressesRouter);
router.use(adminProfileRouter);
router.use(announcementsRouter);
router.use(footerRouter);
router.use(aiRouter);
router.use(failedOrdersRouter);
router.use(adminNotificationsRouter);
router.use(chatRouter);
router.use(reviewsRouter);
router.use(searchRouter);
router.use(imageUploadRouter);
router.use(emailSettingsRouter);
router.use(shippingRouter);
router.use(headerSettingsRouter);
router.use(bidsRouter);
router.use(restockRouter);
router.use(shopifyRouter);
router.use(waInboxRouter);
router.use(socialRouter);
router.use(intelligenceRouter);
router.use(meezanRouter);
router.use(ridersRouter);
router.use(ridersPortalRouter);
router.use(branchesRouter);
router.use(branchInvoiceRouter);
router.use("/admin/erp-settings",  erpSettingsRouter);
router.use("/admin/stock",          branchStockRouter);
router.use("/branch/stock",         branchStockRouter);
router.use("/branch/erp-settings",  erpSettingsRouter);

export default router;
