/** Flat list for ⌘K global search (labels + paths). Keep in sync with main admin routes. */
export const ADMIN_NAV_SEARCH: { href: string; label: string; keywords?: string }[] = [
  { href: "/dashboard", label: "Dashboard", keywords: "home stats" },
  { href: "/analytics", label: "Analytics" },
  { href: "/products", label: "Products", keywords: "catalog sku" },
  { href: "/categories", label: "Categories" },
  { href: "/orders", label: "Orders" },
  { href: "/customers", label: "Customers" },
  { href: "/reviews", label: "Reviews" },
  { href: "/banners", label: "Image Banners" },
  { href: "/video-banners", label: "Video Banners" },
  { href: "/mobile-reels", label: "Mobile Reels" },
  { href: "/coupons", label: "Coupons" },
  { href: "/wallet", label: "Wallet" },
  { href: "/loyalty", label: "Loyalty" },
  { href: "/announcements", label: "Announcements" },
  { href: "/notifications", label: "Notifications" },
  { href: "/import-export", label: "Import / Export" },
  { href: "/integrations", label: "Integrations" },
  { href: "/sync-jobs", label: "Sync Jobs" },
  { href: "/couriers", label: "Couriers" },
  { href: "/shipping-rules", label: "Shipping Rules" },
  { href: "/same-day-delivery", label: "Same Day Delivery" },
  { href: "/payments", label: "Payments" },
  { href: "/failed-orders", label: "Failed Orders" },
  { href: "/location", label: "Location Settings" },
  { href: "/cities", label: "Cities" },
  { href: "/website-settings", label: "Website / Logo Settings" },
  { href: "/header-builder", label: "Header Builder" },
  { href: "/footer", label: "Footer" },
  { href: "/image-optimization", label: "Image Optimization" },
  { href: "/email-settings", label: "Email Settings" },
  { href: "/intelligence", label: "Intelligence" },
  { href: "/profile", label: "My Profile" },
  { href: "/abandoned-checkouts", label: "Abandoned Carts" },
  { href: "/ai-content", label: "AI Content", keywords: "openai chatgpt key" },
  { href: "/blog", label: "Blog / Posts" },
  { href: "/adsense", label: "Blog Ads" },
  { href: "/social-ai", label: "Social AI" },
  { href: "/bidding", label: "Auctions / Bidding" },
  { href: "/restock", label: "Restock Alerts" },
  { href: "/seo/dashboard", label: "SEO Command Center" },
  { href: "/seo", label: "SEO Settings" },
  { href: "/seo/fast-indexing", label: "Fast Indexing" },
  { href: "/seo/merchant-center", label: "Google Merchant" },
  { href: "/seo/redirects", label: "301 Redirects" },
  { href: "/seo/schema", label: "Schema.org" },
  { href: "/seo/ai-writer", label: "AI SEO Writer" },
  { href: "/whatsapp", label: "WhatsApp Settings" },
  { href: "/wa-chat", label: "Unified Inbox" },
  { href: "/wa-inbox", label: "WhatsApp Inbox" },
  { href: "/chat-conversations", label: "Website Chat" },
  { href: "/chat-leads", label: "Chat Leads CRM" },
  { href: "/shopify", label: "Shopify Dashboard" },
  { href: "/shopify/orders", label: "Shopify Orders" },
  { href: "/shopify/customers", label: "Shopify Customers" },
  { href: "/shopify/products", label: "Shopify Products" },
  { href: "/shopify/featured", label: "Featured Products" },
  { href: "/shopify/campaigns", label: "WA Campaigns" },
  { href: "/shopify/email-campaigns", label: "Email Campaigns" },
  { href: "/shopify/marketing", label: "Shopify Marketing Hub" },
  { href: "/shopify/widget", label: "Shopify Chat Widget", keywords: "embed liquid script" },
  { href: "/admin/shopify/widget", label: "Shopify Chat Widget (alias)", keywords: "embed" },
  { href: "/shopify/wa-inbox", label: "Shopify WA Inbox" },
  { href: "/wa-chat/settings", label: "WA Payment Links" },
  { href: "/logistics/live-map", label: "Live Rider Map" },
  { href: "/logistics/delivery-proofs", label: "Delivery proofs", keywords: "rider photo gps dispute cod" },
  { href: "/logistics/lahore", label: "Lahore Deliveries" },
  { href: "/logistics/riders", label: "Riders & Accounting" },
  { href: "/logistics/confirmations", label: "WA Confirmations" },
  { href: "/logistics/automation", label: "Logistics Automation" },
  { href: "/invoice", label: "Invoice & Billing" },
  { href: "/invoice/new", label: "New Invoice" },
  { href: "/payment-gateway", label: "Payment Gateway" },
  { href: "/branches", label: "Branches" },
  { href: "/branches/list", label: "All Branches" },
  { href: "/stock", label: "Stock Overview" },
  { href: "/stock/products", label: "Stock Products" },
  { href: "/stock/movement", label: "Stock Movement" },
  { href: "/stock/adjustment", label: "Stock Adjustment" },
  { href: "/erp-settings", label: "ERP Settings" },
  { href: "/admin/control-center", label: "Enterprise Control Center" },
  { href: "/admin/control-center?tab=users", label: "Admin Users" },
  { href: "/admin/control-center?tab=roles", label: "Roles & Permissions" },
  { href: "/admin/activity-logs", label: "Activity Logs" },
  { href: "/settings/modules", label: "Module Controls" },
  { href: "/pos", label: "Admin POS" },
];
