// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kdf-plus/AccountScreen.tsx": () => import("../components/mockups/kdf-plus/AccountScreen.tsx"),
  "./components/mockups/kdf-plus/CartCheckout.tsx": () => import("../components/mockups/kdf-plus/CartCheckout.tsx"),
  "./components/mockups/kdf-plus/CategoriesScreen.tsx": () => import("../components/mockups/kdf-plus/CategoriesScreen.tsx"),
  "./components/mockups/kdf-plus/CheckoutScreen.tsx": () => import("../components/mockups/kdf-plus/CheckoutScreen.tsx"),
  "./components/mockups/kdf-plus/HomeScreen.tsx": () => import("../components/mockups/kdf-plus/HomeScreen.tsx"),
  "./components/mockups/kdf-plus/LoginScreen.tsx": () => import("../components/mockups/kdf-plus/LoginScreen.tsx"),
  "./components/mockups/kdf-plus/OTPScreen.tsx": () => import("../components/mockups/kdf-plus/OTPScreen.tsx"),
  "./components/mockups/kdf-plus/OnboardingScreen.tsx": () => import("../components/mockups/kdf-plus/OnboardingScreen.tsx"),
  "./components/mockups/kdf-plus/OrderSuccessScreen.tsx": () => import("../components/mockups/kdf-plus/OrderSuccessScreen.tsx"),
  "./components/mockups/kdf-plus/ProductDetail.tsx": () => import("../components/mockups/kdf-plus/ProductDetail.tsx"),
  "./components/mockups/kdf-plus/ProductListingScreen.tsx": () => import("../components/mockups/kdf-plus/ProductListingScreen.tsx"),
  "./components/mockups/kdf-plus/SplashScreen.tsx": () => import("../components/mockups/kdf-plus/SplashScreen.tsx"),
  "./components/mockups/kdf-plus/WalletLoyaltyScreen.tsx": () => import("../components/mockups/kdf-plus/WalletLoyaltyScreen.tsx")
};
