import { pgTable, text, serial, integer, boolean, timestamp, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const bannersTable = pgTable("banners", {
  id: serial("id").primaryKey(),
  title: text("title").default(""),
  subtitle: text("subtitle"),
  imageUrl: text("image_url"),
  mobileImageUrl: text("mobile_image_url"),
  linkUrl: text("link_url"),
  targetType: text("target_type"),
  targetId: integer("target_id"),
  bgColor: text("bg_color").default("from-[#5FA800] to-[#4d8a00]"),
  textColor: text("text_color").default("white"),
  label: text("label"),
  cta: text("cta").default("Shop Now"),
  platform: text("platform").default("both"),
  /** hero | header | promo — keeps storefront sections independent */
  placement: text("placement").notNull().default("hero"),
  sortOrder: integer("sort_order").notNull().default(0),
  active: boolean("active").notNull().default(true),
  countdownEndAt: timestamp("countdown_end_at"),
  startDate: timestamp("start_date"),
  endDate: timestamp("end_date"),
  offerProductIds: jsonb("offer_product_ids").$type<number[]>().default([]),
  offerCategoryIds: jsonb("offer_category_ids").$type<number[]>().default([]),
  offerMode: text("offer_mode").default("discount_products"),
  offerDisplayCount: integer("offer_display_count").notNull().default(8),
  offerSort: text("offer_sort").default("featured"),
  showTimer: boolean("show_timer").notNull().default(true),
  buttonBgColor: text("button_bg_color"),
  buttonTextColor: text("button_text_color"),
  videoUrl: text("video_url"),
  mobileVideoUrl: text("mobile_video_url"),
  videoAutoplay: boolean("video_autoplay").default(true),
  videoMuted: boolean("video_muted").default(true),
  videoLoop: boolean("video_loop").default(true),
  aiMode: boolean("ai_mode").notNull().default(false),
  aiAutoUpdate: boolean("ai_auto_update").notNull().default(false),
  aiCampaign: text("ai_campaign"),
  aiPrompt: text("ai_prompt"),
  aiRefreshCadence: text("ai_refresh_cadence").default("daily"),
  aiLastGeneratedAt: timestamp("ai_last_generated_at"),
  aiNextRefreshAt: timestamp("ai_next_refresh_at"),
  aiSafetyNotes: text("ai_safety_notes"),
  approvedPromotionText: text("approved_promotion_text"),
  healthBenefitText: text("health_benefit_text"),
  urgencyText: text("urgency_text"),
  relatedKeywords: jsonb("related_keywords").$type<string[]>().default([]),
  relatedProductIds: jsonb("related_product_ids").$type<number[]>().default([]),
  bannerStyle: text("banner_style").default("premium"),
  showTitle: boolean("show_title").notNull().default(true),
  showSubtitle: boolean("show_subtitle").notNull().default(true),
  showLabel: boolean("show_label").notNull().default(true),
  showCta: boolean("show_cta").notNull().default(true),
  showExploreCta: boolean("show_explore_cta").notNull().default(false),
  enableAiText: boolean("enable_ai_text").notNull().default(true),
  heroAutoplay: boolean("hero_autoplay").notNull().default(true),
  enableFallbackBanner: boolean("enable_fallback_banner").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const insertBannerSchema = createInsertSchema(bannersTable).omit({
  id: true,
  createdAt: true,
});

export type InsertBanner = z.infer<typeof insertBannerSchema>;
export type Banner = typeof bannersTable.$inferSelect;
